<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Car extends Model
{
    //
    protected $fillable = [
        'brand_id',
        'brand',
        'slug',
        'model',
        'modelArabic',
        'year',
        'capacity',
        'cylinders',
        'horsePower',
        'maxSpeed',
        'numberOfDoors',
        'numberOfSeats',
        'bodyTypeEnglish',
        'bodyTypeArabic'
    ];

    public function brand() {
        return $this->belongsTo('App\Brand');
    }

    public function images() {
        return $this->belongsToMany('App\Image');
    }

    public function features() {
        return $this->hasMany('App\Feature');
    }

    public function delete()
    {
        $images = $this->images->all();
        foreach ($images as $image) {
            Storage::delete($image->url);
            $image->delete;
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
